alias sc='script/console'
alias sg='script/generate'
alias sd='script/destroy'
alias rs='rails server'
alias rc='rails console'
alias rg='rails generate'
alias rd='rails destroy'
alias r='rails'
alias be='bundle exec'
alias ber='bundle exec rake'
alias minitest='bundle exec rake test TEST=$1'
